### ISSUE TITLE
Clarify import instructions

### ISSUE THREAD

**Issue by Caged** [pdxosgeo/pdxbldgimport#36]
The new import instructions are great, @geografa.  There were a couple of places I needed additional clarity since I'm pretty unfamiliar with JOSM.

* The docs use the term "error" when JOSM uses the term "warning."  Sticking with "warning" would help to eliminate any confusion I believe.
* Be explicit about where the commands are located.  I had to hunt around for the validation item and the import existing OSM data item.  Adding the menu paths ( `File -> Download from OSM`) would help here.
* "Run Fix Street Addresses" - This appears to be part of a 3rd party plugin.  Is that correct?  
* It's not clear if we should, without question, fix *all* OSM warnings.  In the couple of tests I'm run, the building data files usually only contain a couple of errors, but when you download the existing OSM data, it contains a bunch of unrelated warnings.  Is the expectation to fix *all* of the warnings?

I'll add the menu paths, but let me know what y'all think about the others.

**Comment by Caged** [comment]
I encountered this ominous sounding error dialog when attempting to merge.  Is this expected? 

<img width="1524" alt="screen shot 2015-07-26 at 11 55 37 am" src="https://cloud.githubusercontent.com/assets/25/8895372/4be491be-338d-11e5-8678-f8a177a87bf1.png">

**Comment by Caged** [comment]
I backed out and ran the "merge selection" step instead. This looks better, but this is still a pretty intimidating error for those that have never encountered it before.  If these dialogs are ok to ignore, let's point that out in the wiki.

<img width="1524" alt="screen shot 2015-07-26 at 11 58 11 am" src="https://cloud.githubusercontent.com/assets/25/8895384/b8784fd2-338d-11e5-830c-7071205ab50d.png">

**Comment by Caged** [comment]
Running the "Fix Street Addresses" plugin, but I can't seem to get it to move beyond this step.  My assumption is that I need to apply the 213 addresses to the Cascade Highway street, but clicking Apply or Assign Addresses doesn't appear to have any effect.

<img width="977" alt="screen shot 2015-07-26 at 12 22 58 pm" src="https://cloud.githubusercontent.com/assets/25/8895480/34177d0e-3391-11e5-9af6-d4c50b9f238e.png">

**Comment by Caged** [comment]
:boom:  I manually fixed the streets, reran validation and verified that everything looked good to the best of my knowledge.  Here's the changeset: https://www.openstreetmap.org/changeset/32896475

Another thing worth pointing out is that you need to authenticate JOSM with your OSM import account. 

<img width="811" alt="screen shot 2015-07-26 at 1 10 51 pm" src="https://cloud.githubusercontent.com/assets/25/8895694/cc9884f0-3397-11e5-8f69-91c89ccdf714.png">

**Comment by Caged** [comment]
I'm using this issue as a catch-all place for import stuff.  LMK if I should break these out into separate issues. 

One issue I'm running into with fixing addresses is Cascade Highway.  That's the common name, but many of the buildings have it listed as "South Highway 213," which is also correct.  If you inspect the highway itself, it has both names listed.

<img width="387" alt="screen shot 2015-07-26 at 1 53 14 pm" src="https://cloud.githubusercontent.com/assets/25/8895867/bb52d870-339d-11e5-8a30-8f558dcdbc97.png">

What should I do in this situation?

**Comment by dobratzp** [comment]
@Caged, overall your imported data looks okay.  I assume that the following are your OSM accounts:

http://www.openstreetmap.org/user/justin_pdxbuildings
http://www.openstreetmap.org/user/justin

Please edit your profile to so there's a hyperlink from one account to the other so that people can more easily find you.

Based on the fact that you only have 1 edit on each account, I would say now is a good time to take a step back and become generally more familiar with the OSM editing process.  The general view is that importing data into OSM is an activity for more experienced OSM contributors.  Start editing the places you frequent: where you live, where you work, where you buy food, etc.  Not only will you become more familiar with how JOSM works, but you will also become more familiar with what kinds of OSM objects to create and what tags to put on them.  Then you can also ask yourself how the data that you are importing would be different from the data that you've entered by hand.

The JOSM validator generates messages at 3 different levels (error, warning, information).  By default, only errors and warnings are generated.  Generally things that the error level are clearly wrong, but the warning level has some false error messages and the information level may contain a lot false messages.  The idea is that as you bring new data into OSM (importing or otherwise), you should not be making the data worse.  For this import, the warning messages to pay most attention to are those involving buildings (overlapping buildings, crossing buildings, etc).  You may also find yourself fixing additional problems with the data as you go and that's fine too.  I've added names to a bunch of previously unnamed roads based on the imported building data.  You are not expected to eliminate all JOSM warning messages.

When you upload the data in JOSM, please enter the following text in the source field to identify the edit as part of the PDX Building Import:
```Portland Metro (http://wiki.openstreetmap.org/wiki/Portland,_OR_Bldg_import#Source_data)```

As you have found out, the Fix Address Plugin is in fact an add-on to JOSM and not installed by default.
http://wiki.openstreetmap.org/wiki/JOSM/Plugins/FixAddresses
I haven't used the plug-in for automatically fixing address, but just identifying them and then fixing them by hand.  I usually select everything in the "Unresolved Addresses" table and then click "Select" and "Close"  Then I hit "3" (Zoom to Selection) and you can usually pick out patterns such as invalidly named roads.  There are usually false positives along the edge of the OSM data you've downloaded where you have the building loaded but the corresponding road is outside of your downloaded area.  If you end up needing to select all of the houses along a certain road, you can use something like the following expression in the JOSM Search box:
```"addr:street"="South Clear View Court"```
I have found that sometimes the FixAddress plug-in does not evaluate all of the addresses prior to the initial upload, so I run FixAddress again after I've uploaded the data.

You notice the presence of tag keys like "name, name_1, name_2, etc."  The general idea is that this form of tagging is not a good idea.  Rather, we should be utilizing name tags as described on the following page:
http://wiki.openstreetmap.org/wiki/Names
The keys "name" and "alt_name" will cover most of the roads that we run across around here.  The idea is that the primary source for the name tag is the actual street sign. You can also try looking at public data provided by the city or county.  Another idea is that you do a USPS zip code lookup on a few addresses along the road to see if they are recognized by the USPS.  In the example, it looks like the USPS recognizes the street name to be "South Highway 213", but does not recognize "Cascade Highway" or "South Molalla Avenue" for some of the house numbers I tried.  The fact that the road is part of a state numbered highway should be indicated by the ref tag and by the inclusion of the Way object in the route relation for the given state highway.  In general, the name tag should not be used for a general description of something, but in this case the actual name of the road may be "South Highway 213".  Often roads will change names as they enter different municipalities.  Before changing the name of a road, check through the OSM history to see if the road was imported or edited by hand.  If the road was edited by hand, think about sending an OSM message to the user(s) who edited the road to see if they agree with your name change.  If you can't fully determine the name of a given road, I would leave the addr:street tags on the buildings alone and make a note of the area so that it can be investigated later.  Make sure to fix obvious errors such as unexpanded abbreviations (TRL, St, etc).

**Comment by Caged** [comment]
Thanks for the detailed response, Peter!  My main account is https://www.openstreetmap.org/user/Caged.  I probably should've created Caged_* account instead.  I linked them up as you suggested.  Also thanks for taking the time to review that changeset. 

For a bit of context, I'm not *completely* new to OSM, but not a seasoned editor by any means.  I use the local data regularly, have spiked out a [previous efforts for importing](https://github.com/Caged/osm-building-import), have read through the building import wiki, [Ian's post](http://www.openstreetmap.org/user/lxbarth/diary/23588) and have worked with Portland's building data for many years.  I still have a lot of blind spots to work through though!  As you can tell, JOSM is one of them.

JOSM and the strategies for bulk editing (automated error checking, bulk merging, etc) are all pretty much a black box to me.  I want to make sure my edits follow the quality and standards of others.

>  The JOSM validator generates messages at 3 different levels (error, warning, information). By default, only errors and warnings are generated. Generally things that the error level are clearly wrong, but the warning level has some false error messages and the information level may contain a lot false messages. The idea is that as you bring new data into OSM (importing or otherwise), you should not be making the data worse. For this import, the warning messages to pay most attention to are those involving buildings (overlapping buildings, crossing buildings, etc). You may also find yourself fixing additional problems with the data as you go and that's fine too. I've added names to a bunch of previously unnamed roads based on the imported building data. You are not expected to eliminate all JOSM warning messages.

Awesome.  This clears up a lot of the questions I had during the validation process.   

>  I usually select everything in the "Unresolved Addresses" table and then click "Select" and "Close" Then I hit "3" (Zoom to Selection) and you can usually pick out patterns such as invalidly named roads.

This is what I ended up doing and it appears to have worked pretty well.  

> I have found that sometimes the FixAddress plug-in does not evaluate all of the addresses prior to the initial upload, so I run FixAddress again after I've uploaded the data.

Good to know.  Do you do this directly after the upload in the same working JOSM "project" or do you start fresh and redownload the existing area? 

> Another idea is that you do a USPS zip code lookup on a few addresses along the road to see if they are recognized by the USPS.

Nice.

Thanks again!  Your comment was incredibly helpful.

**Comment by dobratzp** [comment]
Thanks for clarifying.  To answer your question about merging the data, I think the way to go is to select all objects in the layer of the OSM data to be imported and then merge into a new data layer of OSM data that you have downloaded from the main OSM site as you have done.  The error message is expected as it's generally not a good idea to import data without going through the import process as we have done.

I re-run FixAddresses right after uploading and it catches more errors.  Then I fix them and upload again.

I see that you've run into another common error our source data.  Names starting with "Mc" are not capitalized correctly.  Please change your the addr:street tags on your buildings: 
"South Mcburney Road" => "South McBurney Road"

Between quarter sections, I quit out of JOSM and come back in so that my changeset bounding box doesn't grow beyond the current quarter section.

**Comment by Caged** [comment]
I think this is closable now.
